#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app/config/routing.yml

places:
    type:     rest
    resource: App\Controller\PlaceController

prices:
    type:     rest
    resource: App\Controller\Place\PriceController

users:
    type:     rest
    resource: App\Controller\UserController
themes:
    type:     rest
    resource: App\Controller\Place\ThemeController
preferences:
    type:     rest
    resource: App\Controller\User\PreferenceController
